package org.schabi.newpipe.extractor.services.youtube.extractors;

import com.grack.nanojson.JsonObject;
import org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper;
import org.schabi.newpipe.extractor.services.youtube.stream.ColorInfo;
import org.schabi.newpipe.extractor.services.youtube.stream.Itag;
import org.schabi.newpipe.extractor.stream.AudioTrackType;
import org.schabi.newpipe.extractor.stream.interfaces.base.BaseVideoStream.ProjectionType;
import org.schabi.newpipe.extractor.stream.mediaformat.AudioMediaFormat;
import org.schabi.newpipe.extractor.stream.mediaformat.SubtitlesMediaFormat;
import org.schabi.newpipe.extractor.stream.mediaformat.VideoMediaFormat;
import org.schabi.newpipe.extractor.utils.LocaleCompat;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Locale;

/**
 * Utility class to get media formats from Itag IDs and Itag data from a format in a player
 * response.
 *
 * <p>
 * Itag list and their media format are based on
 * <a href="https://gist.github.com/MartinEesmaa/2f4b261cb90a47e9c41ba115a011a4aa">
 * this GitHub Gist</a>.
 * </p>
 */
final class ItagUtils {

    private ItagUtils() {
    }

    @Nullable
    static AudioMediaFormat getAudioMediaFormatFromItagId(final int itagId) {
        return switch (itagId) {
            case 18, // Muxed streams AAC
                 139, 140, 141, 599, // AAC (141 is Premium)
                 233, 234, 235, // AAC HLS (235 is Premium)
                 256, 258, 327, // AAC Surround
                 328, // EAC3 Surround
                 773, // IAMF Opus
                 380 -> AudioMediaFormat.M4A; // AC3
            case 249, 250, 251, 600, 774, // Opus (774 is Premium)
                 338 -> AudioMediaFormat.WEBM; // Spatial Opus
            default -> null;
        };
    }

    @Nullable
    static VideoMediaFormat getVideoMediaFormatFromItagId(final int itagId) {
        return switch (itagId) {
            case 18, // Muxed streams H.264
                 91, 92, 93, 94, 95, 96, 300, 301, // Muxed streams H.264 from adaptive Itags
                 133, 134, 135, 136, 137, 160, 214, 264, 266, 298, 299, 304, 305, 597, // H.264
                 229, 230, 231, 232, 269, 270, 311, 312, 379, // H.264 HLS
                 394, 395, 396, 397, 398, 399, 400, 401, 402, 571, 694, 695, 696, 697, 698, 699,
                 700, 701, 702, 721, 788 // AV1 (721 is Premium)
                    -> VideoMediaFormat.MP4;
            case 242, 243, 244, 247, 248, 271, 272, 278, 302, 303, 308, 313, 315, 330, 331, 332,
                 333, 334, 335, 336, 337, 356, 598, 779, 780, // VP9 (356 is Premium)
                 602, 603, 604, 605, 609, 612, 614, 616, 617, 620, 625, // VP9 HLS (616 is Premium)
                 787 // AV1
                    -> VideoMediaFormat.WEBM;
            default -> null;
        };
    }

    @Nullable
    static SubtitlesMediaFormat getSubtitlesMediaFormatFromItagId(final int itagId) {
        return switch (itagId) {
            case 386, 387, 406 -> SubtitlesMediaFormat.MP4;
            default -> null;
        };
    }

    @Nonnull
    static ProjectionType getProjectionTypeFromString(@Nullable final String projectionType) {
        if (projectionType == null) {
            return ProjectionType.UNKNOWN;
        }

        return switch (projectionType) {
            case "RECTANGULAR" -> ProjectionType.RECTANGULAR;
            case "MESH" -> ProjectionType.MESH;
            case "EQUIRECTANGULAR" -> ProjectionType.EQUIRECTANGULAR;
            case "EQUIRECTANGULAR_THREED_TOP_BOTTOM" ->
                    ProjectionType.EQUIRECTANGULAR_THREED_TOP_BOTTOM;
            default -> ProjectionType.UNKNOWN;
        };
    }

    record AudioItagData(@Nullable Integer sampleRate,
                         @Nullable Integer channelsCount,
                         @Nonnull AudioTrackType trackType,
                         @Nullable Double loudnessDb,
                         @Nullable Double trackAbsoluteLoudnessLkfs,
                         @Nullable Locale locale,
                         @Nonnull Boolean isDrc,
                         @Nonnull Boolean isAutoGenerated) {
    }

    @Nonnull
    static AudioItagData getItagDataFromAudioFormat(@Nonnull final JsonObject format) {
        Integer sampleRate;
        try {
            sampleRate = Integer.parseInt(format.getString("audioSampleRate"));
            if (sampleRate <= 0) {
                // Bad value returned by YouTube or data missing, return
                // unknown in this case
                sampleRate = null;
            }
        } catch (final NumberFormatException e) {
            sampleRate = null;
        }

        final int channelsCount = format.getInt("audioChannels", -1);
        final Integer channelsCountObj = channelsCount == -1 ? null : channelsCount;

        final String xtags = format.getString("xtags");

        AudioTrackType audioTrackType = YoutubeParsingHelper.extractAudioTrackType(xtags);
        if (audioTrackType == null) {
            // No audio track type info, this means there should be only one track which is the
            // original (or in the case of a muxed format only the original audio)
            audioTrackType = AudioTrackType.ORIGINAL;
        }

        final Locale locale;
        final String languageCode = YoutubeParsingHelper.extractFirstKeyFromXtags(
                xtags, "lang");
        if (languageCode == null) {
            locale = null;
        } else {
            locale = LocaleCompat.forLanguageTag(languageCode)
                    .orElse(null);
        }

        // As loudnessDb and trackAbsoluteLoudnessLkfs may be negative or positive (?), we can't
        // use a specific fallback value as a property existence check, so check first the presence
        // of the properties
        final Double loudnessDb = format.has("loudnessDb") ? format.getDouble("loudnessDb") : null;
        final Double trackAbsoluteLoudnessLkfs = format.has("trackAbsoluteLoudnessLkfs")
                ? format.getDouble("trackAbsoluteLoudnessLkfs") : null;

        return new AudioItagData(sampleRate, channelsCountObj, audioTrackType, loudnessDb,
                trackAbsoluteLoudnessLkfs, locale, format.getBoolean("isDrc"),
                format.getBoolean("isAutoDubbed") || format.getBoolean("isVb"));
    }

    record VideoItagData(@Nullable Integer width,
                         @Nullable Integer height,
                         @Nullable Integer fps,
                         @Nullable String qualityLabel,
                         @Nonnull ProjectionType projectionType,
                         boolean isHdr,
                         @Nullable ColorInfo colorInfo,
                         @Nonnull Boolean isAutoGenerated) {
    }

    @Nonnull
    static VideoItagData getItagDataFromVideoFormat(@Nonnull final JsonObject format) {
        Integer width = Integer.parseInt(format.getString("width"));
        if (width < 0) {
            // Bad value returned by YouTube or data missing, return
            // unknown in this case
            width = null;
        }

        Integer height = Integer.parseInt(format.getString("height"));
        if (height < 0) {
            // Bad value returned by YouTube or data missing, return
            // unknown in this case
            height = null;
        }

        Integer fps = Integer.parseInt(format.getString("fps"));
        if (fps < 0) {
            // Bad value returned by YouTube or data missing, return
            // unknown in this case
            fps = null;
        }

        final ColorInfo colorInfo;
        if (format.has("colorInfo")) {
            final JsonObject colorInfoJsonObj = format.getObject("colorInfo");
            colorInfo = new ColorInfo(colorInfoJsonObj.getString("primaries"),
                    colorInfoJsonObj.getString("transferCharacteristics"),
                    colorInfoJsonObj.getString("matrixCoefficients"));
        } else {
            colorInfo = null;
        }

        final String qualityLabel = format.getString("qualityLabel");

        return new VideoItagData(width, height, fps, qualityLabel, getProjectionTypeFromString(
                format.getString("projectionType")),
                qualityLabel != null && qualityLabel.contains("HDR"), colorInfo,
                "1".equals(YoutubeParsingHelper.extractFirstKeyFromXtags(
                        format.getString("xtags"), "sr")));
    }

    @Nonnull
    static Itag buildItagFromFormat(@Nonnull final JsonObject format,
                                    final int itagId) {
        Integer targetDurationSec = format.getInt("targetDurationSec", -1);
        if (targetDurationSec == -1) {
            targetDurationSec = null;
        }

        Integer maxDvrDurationSec = format.getInt("maxDvrDurationSec", -1);
        if (maxDvrDurationSec == -1) {
            maxDvrDurationSec = null;
        }

        final JsonObject initRange = format.getObject("initRange");

        Integer initRangeStart;
        try {
            initRangeStart = Integer.parseInt(initRange.getString("start"));
        } catch (final NumberFormatException e) {
            initRangeStart = null;
        }

        Integer initRangeEnd;
        try {
            initRangeEnd = Integer.parseInt(initRange.getString("end"));
        } catch (final NumberFormatException e) {
            initRangeEnd = null;
        }

        final JsonObject indexRange = format.getObject("indexRange");

        Integer indexRangeStart;
        try {
            indexRangeStart = Integer.parseInt(indexRange.getString("start"));
        } catch (final NumberFormatException e) {
            indexRangeStart = null;
        }

        Integer indexRangeEnd;
        try {
            indexRangeEnd = Integer.parseInt(indexRange.getString("end"));
        } catch (final NumberFormatException e) {
            indexRangeEnd = null;
        }

        Long lastModifiedTimestamp;
        try {
            lastModifiedTimestamp = Long.parseLong(format.getString("lastModified"));
        } catch (final NumberFormatException e) {
            lastModifiedTimestamp = null;
        }

        return new Itag(itagId, format.getString("xtags"), targetDurationSec, maxDvrDurationSec,
                initRangeStart, initRangeEnd, indexRangeStart, indexRangeEnd,
                lastModifiedTimestamp);
    }
}
