package org.schabi.newpipe.extractor.stream.interfaces.base;

import javax.annotation.Nullable;
import java.util.Locale;

/**
 * Base interface for a demuxed stream, which contains only one type of data and can be aggregated
 * in a {@link BaseMuxedStream}.
 *
 * <p>
 * It does not represent the base of demuxed streams to be directly used by clients, but the one of
 * extractor sub-definitions and custom implementations. See
 * {@link org.schabi.newpipe.extractor.stream.interfaces.DemuxedStream DemuxedStream} for an
 * interface to be used directly.
 * </p>
 */
public interface BaseDemuxedStream extends BaseStream {

    /**
     * Get the language of this stream as a {@link Locale} if it is known or applicable
     *
     * @return a {@link Locale} describing the language of this stream or {@code null}
     */
    @Nullable
    Locale getLocale();

    /**
     * Get whether this stream has been automatically generated by the service.
     *
     * <p>
     * Examples of automatically generated streams include video with their resolution upscaled,
     * automatic dubbed audio tracks, generated subtitles based on the audio and/or in another
     * language.
     * </p>
     *
     * <p>
     * Streams generated from classic transcodings/conversions of an original audio file are not
     * considered as automatically generated.
     * </p>
     *
     * <p>
     * If this is not known, {@code null} should be returned.
     * </p>
     *
     * @return whether this stream has been automatically generated by the service or {@code null}
     */
    @Nullable
    Boolean isAutomaticallyServiceGenerated();
}
