package org.schabi.newpipe.extractor.services.youtube.stream;

import org.schabi.newpipe.extractor.stream.impl.base.BaseSubtitlesStreamImpl;
import org.schabi.newpipe.extractor.stream.mediaformat.SubtitlesMediaFormat;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.List;
import java.util.Locale;

/**
 * Base class for subtitles demuxed streams of YouTube livestreams and ended livestreams, which
 * have been not reencoded yet.
 *
 * <p>
 * Instances of this class aren't meant to be built by extractor users, only YouTube extractors.
 * </p>
 */
public class YoutubeBaseLiveSubtitlesDemuxedStream extends BaseSubtitlesStreamImpl
        implements YoutubeBaseDemuxedStream {

    @Nonnull
    private final Itag itag;

    /**
     * Construct a new {@link YoutubeBaseLiveSubtitlesDemuxedStream} instance.
     *
     * @param id                              the ID of the stream, which should be of the form
     *                                        {@code InnerTube_client_name-Itag_ID}
     * @param name                            the displayed name of the stream in the subtitles
     *                                        settings ({@code displayName} property)
     * @param locale                          a {@link Locale} built with the value of the
     *                                        {@code languageCode} property
     * @param isAutomaticallyServiceGenerated whether captions are automatically generated by
     *                                        YouTube
     * @param mediaFormat                     an appropriate {@link SubtitlesMediaFormat} value
     *                                        based on the {@code mimeType} property returned
     * @param itag                            an {@link Itag} instance for this stream
     */
    public YoutubeBaseLiveSubtitlesDemuxedStream(
            @Nonnull final String id,
            @Nullable final String name,
            @Nullable final Locale locale,
            @Nullable final Boolean isAutomaticallyServiceGenerated,
            @Nonnull final SubtitlesMediaFormat mediaFormat,
            @Nonnull final Itag itag) {
        // Live and post live subtitles should not have translations from them
        super(id, name, locale, isAutomaticallyServiceGenerated, mediaFormat, List.of());
        this.itag = itag;
    }

    @Nonnull
    @Override
    public Itag getItag() {
        return itag;
    }

    @Override
    public boolean equals(final Object o) {
        if (!(o instanceof YoutubeBaseLiveSubtitlesDemuxedStream that) || !super.equals(o)) {
            return false;
        }

        return itag.equals(that.itag);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + itag.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "YoutubeBaseLiveSubtitlesStream{"
                + "id=" + getId()
                + ", name=" + getName()
                + ", locale=" + getLocale()
                + ", isAutomaticallyServiceGenerated=" + isAutomaticallyServiceGenerated()
                + ", mediaFormat=" + getMediaFormat()
                + ", translations=" + getTranslations()
                + ", itag=" + itag
                + "}";
    }
}
