package org.schabi.newpipe.extractor.services.youtube.stream;

import org.schabi.newpipe.extractor.stream.StreamingProtocol;
import org.schabi.newpipe.extractor.stream.deliverysource.DeliverySource;
import org.schabi.newpipe.extractor.stream.interfaces.Stream;
import org.schabi.newpipe.extractor.stream.mediaformat.SubtitlesMediaFormat;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Locale;

/**
 * Class representing subtitles demuxed streams of YouTube livestreams and ended livestreams, which
 * have been not reencoded yet and available with an individual streaming URL.
 *
 * <p>
 * Subtitles of regular videos are stored in
 * {@link org.schabi.newpipe.extractor.stream.impl.UriSubtitlesStream UriSubtitlesStream} instances.
 * </p>
 *
 * <p>
 * Instances of this class aren't meant to be built by extractor users, only YouTube extractors.
 * </p>
 */
public final class YoutubeUriLiveSubtitlesStream extends YoutubeBaseLiveSubtitlesDemuxedStream
        implements Stream {

    @Nonnull
    private final DeliverySource deliverySource;

    /**
     * Construct a new {@link YoutubeUriLiveSubtitlesStream} instance
     *
     * @param id                              the ID of the stream, which should be of the form
     *                                        {@code InnerTube_client_name-Itag_ID}
     * @param name                            the displayed name of the stream in the subtitles
     *                                        settings ({@code displayName} property)
     * @param locale                          a {@link Locale} built with the value of the
     *                                        {@code languageCode} property
     * @param isAutomaticallyServiceGenerated whether captions are automatically generated by
     *                                        YouTube
     * @param mediaFormat                     an appropriate {@link SubtitlesMediaFormat} value
     *                                        based on the {@code mimeType} property returned
     * @param itag                            an {@link Itag} instance for this stream
     * @param deliverySource                  the {@link DeliverySource} of the stream, which
     *                                        should contain the streaming URL in the {@code url}
     *                                        property and fallback URLs, constructed from the
     *                                        second part of the {@code mn} query parameter from
     *                                        this URL and with the
     *                                        {@code redirector.googlevideo.com} domain
     */
    public YoutubeUriLiveSubtitlesStream(@Nonnull final String id,
                                         @Nullable final String name,
                                         @Nullable final Locale locale,
                                         @Nullable final Boolean isAutomaticallyServiceGenerated,
                                         @Nonnull final SubtitlesMediaFormat mediaFormat,
                                         @Nonnull final Itag itag,
                                         @Nonnull final DeliverySource deliverySource) {
        super(id, name, locale, isAutomaticallyServiceGenerated, mediaFormat, itag);
        this.deliverySource = deliverySource;
    }

    @Nonnull
    @Override
    public DeliverySource getDeliverySource() {
        return deliverySource;
    }

    @Nonnull
    @Override
    public StreamingProtocol getStreamingProtocol() {
        return StreamingProtocol.DASH;
    }

    @Override
    public boolean equals(final Object o) {
        if (!(o instanceof YoutubeUriLiveSubtitlesStream that) || !super.equals(o)) {
            return false;
        }

        return deliverySource.equals(that.deliverySource);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + deliverySource.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "YoutubeUriLiveSubtitlesStream{"
                + "id=" + getId()
                + ", name=" + getName()
                + ", locale=" + getLocale()
                + ", isAutomaticallyServiceGenerated=" + isAutomaticallyServiceGenerated()
                + ", mediaFormat=" + getMediaFormat()
                + ", translations=" + getTranslations()
                + ", itag=" + getItag()
                + ", deliverySource=" + deliverySource
                + "}";
    }
}
